### ISSUE TITLE
Variants in unify

### ISSUE THREAD

**Issue by atennapel** [willtim/row-polymorphism#1]
In the ConstrainedRows version `TVariant` does not appear in unify.
Is it the same as `TRecord`?
```
unify (TVariant row1) (TVariant row2) = unify row1 row2
```
Also in Injection the type is:
```
Inj label : t -> Var {label : t | r}
```
I understand the `r` in this case, without it two variant couldn't be combined.
But for example `Inj Just 5`, in this case the type is `Var {Just : Int | r}`, didn't we lose information now, since we know that this variant will only have a `Just` label, but after injection it can be more than just `Just`.
Is this the wrong way to look at row polymorphism?

**Comment by willtim** [comment]
Hi, well spotted, the missing unification case for TVariant would indeed be how you have written it.
Regarding your question about the injection primitive, I will need to give a bit of explanation.

The variant injection primitive is the dual to record selection, here they are for comparison, using your notation:
```
Sel label : Rec {label : t | r} -> t
Inj label : t -> Var {label : t | r}
```

Injection is how one would introduce Variants, case analysis is how we might want to eliminate them. Ignoring syntax, we would expect the primitive used in a case analysis construct to be something like:

`elim:  ( Var {l:a | r} , a->b, <r> -> b ) -> b
`
So a syntax such as:
`\ x -> case x of { Foo y -> y; Bar -> 2; _ -> 3 }
`
Would desugar to:
`\ x -> elim (x ,  id, \x' -> elim (x', const 2, const 3))
`

Note the types of x and x' are both polymorphic types, with x' having the Bar label but not the Foo label. 
If we were to bind this function to "f" it would have the following type:

`f : Var {Foo : Int, Bar : () | r} -> Int
`
Now if our injection primitive was not polymorphic, but instead was "closed", e.g. a "Foo 1" literal expression has type Var {Foo: Int}, then we would get a type error if we tried to apply f to it, e.g. "f (Foo 1)".
So hopefully you can see that injection generally needs to be polymorphic.

If you ever did need to "close" the variant, then you just have to make the result monomorphic by supplying a type annotation. E.g.  (Inj Just 5 : Var {Just : Int}).

**Comment by atennapel** [comment]
I see, thank you!

I am experimenting with row polymorphism and I'm also trying to infer recursive types:
```
let Nil = inj Nil ()
let Cons h t = inj Cons {head = h, tail = t}

let rec sum list =
  case list of
    Nil -> \() -> 0
    Cons -> \r -> r.head + (sum r.tail)

sum : mu t . (Var {Nil: (), Cons: (Rec {head: Int, tail: t | r/{head, tail})}) -> Int
```
Of course using Cons and Nil will not infer a recursive type, but will instead infer a nested type:
```
Cons 1 (Cons 2 (Cons 3 Nil)) :
(Var {Cons: (Rec {head: Int, tail: (Var {Cons: (Rec {head: Int, tail: (Var {Cons: (Rec {head: Int, tail: (Var {Nil: () | r/{Nil}})}) | r1/{Cons}})}) | r2/{Cons}})}) | r3/{Cons}})
```
Do you see any solution to this without using type annotations? Or are non-row polymorphic ADTs the only sane solution to recursive variants?
In some way Cons should get a recursive type:
```
Cons :
  h ->
  mu t . (Var {Nil: (), Cons: (Rec {head: h, tail: t})}) ->
  mu t . (Var {Nil: (), Cons: (Rec {head: h, tail: t})})
```
I'm sorry if these questions are silly and I'm wasting your time, I'm quite new to this stuff :)

**Comment by willtim** [comment]
No problem, you are the first comment I've had!  
I think we will need a "Fix" type in order to build a cons list, is this what your "mu "type is? This could be a primitive built-in type, if we don't want to support ADTs in our hypothetical language.
A cons list would thus have the type:

`type List a = Fix (\r -> Var { head : a, tail : r }) 
`
Note that I'm using a type lambda in my notation, but newtypes or similar would suffice.
Using Fix to tie the knot is also very useful for ADTs of course, parameterised recursion leads to better datatype extensibility and composition.

EDIT:
To make your summation function work, we would need to use the Fix type eliminator, unFix :
```
let rec sum list =
  case unFix list of
    Nil -> \() -> 0
    Cons -> \r -> r.head + (sum r.tail)
```

```
Fix : f (Fix f) -> Fix f
unFix : Fix f -> f (Fix f)
```

**Comment by atennapel** [comment]
This repository has been a big help in implementing row polymorphism! I find the papers on it hard to read. Thanks for that!

Yes the `mu` I used is the same as `Fix`:
```
mu r . Var { head : a, tail : r } <-> Fix (\r -> Var { head : a, tail : r })
```
How I do it at the moment is that during unification `mu` gets unwrapped by one level
```
mu r . Var { head : a, tail : r } -> Var { head : a, tail : mu r . Var { head : a, tail : r } }
```

Imagine a language with full inference and no way to specify type annotations or define types.
Then row polymorphism is a big help. The records and "ADTs" can be inferred from the code, without the them being defined in advance. Is there any way to define a `List t` in such a language? Even if you could define a type such as you did in your post, you wouldn't be able to use it, since you cannot annotate your function. I'm rambling a bit, but I'm just brainstorming if my language really needs type annotations and if full inference can work well.

Now the following can never get a recursive type, since the function itself is not recursive:
```
let Cons h t = inj Cons (h, t)
```
I think that if you define a kind of recursive id function over `Cons` it might be possible to infer a recursive type for the return value.
```
let rec cons h t =
  case t of {
    Nil () -> inj Cons (h, inj Nil ()) 
    Cons (h', t') -> inj Cons (h, cons h' t')
  }

let Nil = inj Nil ()

cons 1 (cons 2 (cons 3 Nil) : forall t p . (mu r . Var {Nil : (), Cons : (t, r | p)})
```
What are your ideas/opinions on this?

**Comment by willtim** [comment]
I believe it should be possible without type annotations as long as we keep to basic extensions of the Hindley-Milner type system.  For example, consider:

```
let rec sum list =
  case unFix list of
    Nil -> \() -> 0
    Cons -> \r -> r.head + (sum r.tail)
```

and the type of unFix:

`unFix : Fix f -> f (Fix f)
`
The goal here is for the type checker to infer the following type for sum:

`sum : Fix (\r -> Var { head : Int, tail : r }) -> Int
`
The type lambda is just notation, but we do need some sort of mechanism for abstracting "Var { head : a, tail : r }" over r.  If we can support higher-kinds and a way of abstracting over r (easy if there is only one type variable), then I think what you propose is possible.

**Comment by atennapel** [comment]
Ah okay, yeah unFix would work nicely.

First I will try to do it without unFix though. Since there is a recursive call we know that `list ~ tail`, the inference algorithm should be able to figure out that it must be a recursive type. Some part of the input must be the same as the input. `occurs` should no longer makes the type checking fail (at least in `let rec`).
```
in sum:
list : Var {Nil: (), Cons: Rec {head: t, tail: r | p}}
list ~ r
r ~ Var {Nil: (), Cons: Rec {head: t, tail: r | p}}
occurs(r, Var {Nil: (), Cons: Rec {head: t, tail: r | p}})
r -> mu rec . Var {Nil: (), Cons: Rec {head: t, tail: rec | p}}
```
