### ISSUE TITLE
Possibly modify newTyVar to use integers rather than `a` / `r` prefix

### ISSUE THREAD

**Issue by 7sharp9** [willtim/row-polymorphism#3]
Hi, first thanks for putting up this resource :-)

I wondered if it would be more efficient to just use integers for `newTyVar` in the row polymorphism implementation?

https://github.com/willtim/row-polymorphism/blob/master/src/AlgorithmW_Records.hs#L125

Rather than adding a "r" or "a" prefix on each generation of a new TyVar?

**Comment by willtim** [comment]
Hi, yes it would be more efficient to use ints and IntMap, but I wanted to make minimal adaptions to the original source code described in the paper "Algorithm W Step-by-Step" and this is how the original author chose to implement the type environment.  For a more complete type checker with row types, please see the "Expresso" repository, which does indeed use ints, at least for the meta-type-variables.
